version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: webflux
      POSTGRES_USER: user_username
      POSTGRES_PASSWORD: user_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: